### ISSUE TITLE
Tara_backup条目在手动删除后无法再次出现

### ISSUE THREAD

**Issue by cesaryuan** [l0o0/tara#1]
刚才创建了一个备份，然后看到出现了一个Tara_backup条目，尝试手动把它删除了，现在再次创建备份会提示已经保存到Tara_backup条目，但是却搜不到这个条目了
![image](https://user-images.githubusercontent.com/35998162/210242247-95be69a6-6190-45ff-855e-32736c8a509c.png)

**Comment by l0o0** [comment]
你删除的时候，可能这个条目还在回收站里，没有清空？然后你恢复之后，这个又出现了？

**Comment by cesaryuan** [comment]
> 你删除的时候，可能这个条目还在回收站里，没有清空？然后你恢复之后，这个又出现了？

嗯嗯，发现了😂
