### ISSUE TITLE
毫无效果，且打开软件出现错误提示

### ISSUE THREAD

**Issue by suborigin** [l0o0/tara#10]
我用windows备份了，试图用mac恢复，但是win上新安装插件并没有在mac装上，还出现了这个bug提示。如何解决？？
![848BBF73F6C279B230A602CD4F41A9E3](https://user-images.githubusercontent.com/5853668/223598686-b481a3b1-ebe2-480b-b3c4-5c6c801b93ec.jpg)

**Comment by l0o0** [comment]
这个太难了。你windows备份的zip文件，导入到Zotero后，恢复时有没有出现什么错误提示？还是说Tara插件根本在Mac上就装不上？

**Comment by suborigin** [comment]
> 

你好，并没有错误提示，也能装上，就有这个问题，卸载了到现在还有

**Comment by l0o0** [comment]
请更新最新版试试
