### ISSUE TITLE
请问此插件可以备份快捷键的设置和编辑器里的修改吗？

### ISSUE THREAD

**Issue by Xieleilab** [l0o0/tara#15]
![image](https://user-images.githubusercontent.com/78771561/231325397-654e856a-d194-4a58-a001-6b0262a632c3.png)
![image](https://user-images.githubusercontent.com/78771561/231325505-d99691d5-db59-4164-9c13-b0c537929a45.png)

**Comment by zoushucai** [comment]
我最近也遇到了这个问题, 备份以后恢复,只保留了插件,插件中的很多配置信息都需要重新设置, 希望作者能提供可以保持插件信息的选项吧,

**Comment by zzzop** [comment]
目前我试着是不行

**Comment by l0o0** [comment]
Zutilo的配置和其他插件不一样，其他插件是`extensions.zotero.xxx`，这个是`extensions.zutilo.xxx`。
