### ISSUE TITLE
【导出】备份的作用是什么

### ISSUE THREAD

**Issue by cesaryuan** [l0o0/tara#2]
首先感谢大佬制作这个方便好用的扩展😁，我现在关于扩展的功能有一个小疑问，就是：

创建备份的意思我懂了，就是创建一个Tara_backup条目，然后在【恢复】时，Tara会读取Tara_backup条目下面的备份zip。
那么【导出】功能的作用是什么呢，我尝试【导出】了一个备份，然后点击【恢复】，发现备份文件列表是空的，也没有地方手动选择备份文件。

![image](https://user-images.githubusercontent.com/35998162/210242954-3985b4f5-75eb-4047-8652-e07d8f2eedb1.png)

**Comment by l0o0** [comment]
导出是把当前的配置等信息导出到一个本地的目录里，就是在Zotero 目录下的Backup目录里，目前这个目录还不能自定义设置。导出的时候，并不会在Tara_backup条目里增加一个附件。

这个导出的本意是做想跨电脑间的备份和恢复。比如你把一台电脑的配置导出来，然后把这个文件放到另一台电脑上，当你点恢复的时候，会出现一个选择文件的窗口，进行恢复。

**Comment by cesaryuan** [comment]
谢谢，了解啦
