### ISSUE TITLE
插件不能同步

### ISSUE THREAD

**Issue by ydniuyongjie** [l0o0/tara#21]
安装的0.03版本，恢复的时候提示如下图：
![image](https://github.com/l0o0/tara/assets/42044877/4fb35665-e8d8-4551-be9d-1539f946126b)
插件也没有安装，
我原先认为是插件版本太低，所以想安装高一点的版本，下载了1.0.2版本，安装提示为：
![image](https://github.com/l0o0/tara/assets/42044877/084888b4-25ef-4635-81a1-219b7fee00a8)
我的zotero插件是6.0.30版本。
请大佬给我看看是什么原因

**Comment by l0o0** [comment]
在解压缩文件的时候出错了，你方便把输出日志复制上来么？记得操作过后，把日志附上。应该会在最日志最前面反馈重要的错误信息
![图片](https://github.com/l0o0/tara/assets/2743744/c2c0e46c-a4c9-49dd-ad4c-6cfb6f8db534)


1.xxx 版本是只兼容 Zotero7。

**Comment by ydniuyongjie** [comment]
日志信息如下：
(3)(+0000434): NS_ERROR_FILE_NOT_FOUND Exception: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIZipReader.extract] unzipToTemporaryDir/<@chrome://tara/content/scripts/index.js:624:11 fulfilled@chrome://tara/content/scripts/index.js:10:16

(3)(+0000002): NS_ERROR_FILE_NOT_FOUND Exception: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFileInputStream.init] Zotero.File</this.getContents@chrome://zotero/content/xpcom/file.js:167:7 restoreFromFile/<@chrome://tara/content/scripts/index.js:707:17 rejected@chrome://tara/content/scripts/index.js:17:16

(3)(+0000785): Getting contents of E:\zotero\tmp\Backup\backup.json

(3)(+0000003): Error: Win error 2 during operation open on file E:\zotero\tmp\Backup\backup.json (系统找不到指定的文件。 ) (No stack trace) From previous event: restoreFromFile/<@chrome://tara/content/scripts/index.js:788:23 fulfilled@chrome://tara/content/scripts/index.js:10:16

(3)(+0020633): {better-bibtex} +53439 idle: Mon Nov 27 2023 21:46:17 GMT+0800, save-database idle

**Comment by l0o0** [comment]
@ydniuyongjie 从什么操作系统到什么操作系统备份的

**Comment by ydniuyongjie** [comment]
win11，在本机上先“创建”，然后直接“恢复”，就出现这样的错误提示。没有换计算机，直接在本机上进行实验。
![image](https://github.com/l0o0/tara/assets/42044877/d250051d-2964-46fa-8e01-054090ac6b6f)

**Comment by ydniuyongjie** [comment]
比较完整的日志，好像是在E:\zotero\tmp\Backup\找不到文件

(4)(+0003158): SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND itemID IN (SELECT itemID FROM itemData WHERE (fieldID IN (?,?,?,?) AND valueID IN (SELECT valueID FROM itemDataValues WHERE value=?))) [1, 45, 60, 97, 'Tara_Backup']

(3)(+0000015): [ "0": "2023/11/28 上午8:33:00_backup.zip" ]

(3)(+0000000): ** Tara open select window

(3)(+0002295): ** Tara Tara select promise

(3)(+0000000): 2023/11/28 上午8:33:00_backup.zip

(3)(+0000000): ** Tara open window

(3)(+0000016): ** Tara wait

(3)(+0000029): ** Tara wait

(3)(+0000001): E:\zotero\tmp\Backup

(3)(+0000420): NS_ERROR_FILE_NOT_FOUND Exception: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIZipReader.extract] unzipToTemporaryDir/<@chrome://tara/content/scripts/index.js:624:11 fulfilled@chrome://tara/content/scripts/index.js:10:16

(3)(+0000001): NS_ERROR_FILE_NOT_FOUND Exception: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFileInputStream.init] Zotero.File</this.getContents@chrome://zotero/content/xpcom/file.js:167:7 restoreFromFile/<@chrome://tara/content/scripts/index.js:707:17 rejected@chrome://tara/content/scripts/index.js:17:16

(3)(+0000670): Getting contents of E:\zotero\tmp\Backup\backup.json
(3)(+0000002): Error: Win error 2 during operation open on file E:\zotero\tmp\Backup\backup.json (系统找不到指定的文件。 ) (No stack trace) From previous event: restoreFromFile/<@chrome://tara/content/scripts/index.js:788:23 fulfilled@chrome://tara/content/scripts/index.js:10:16

(3)(+0009310): Getting contents of C:\Users\NWU\AppData\Roaming\Zotero\Zotero\Profiles\jxnjauhx.default\treePrefs.json

(3)(+0000002): Writing column prefs of length 7807 to file C:\Users\NWU\AppData\Roaming\Zotero\Zotero\Profiles\jxnjauhx.default\treePrefs.json

**Comment by l0o0** [comment]
[tara.xpi.zip](https://github.com/l0o0/tara/files/13482235/tara.xpi.zip)

@ydniuyongjie 试试这个脚本，我特意加了一些日志。你运行后，给我看看

**Comment by ydniuyongjie** [comment]
文件很大，我一行都没动，直接发给你一个文件
[日志.txt](https://github.com/l0o0/tara/files/13482383/default.txt)
希望对你有用。

**Comment by l0o0** [comment]
谢谢

**Comment by ydniuyongjie** [comment]
我要感谢你，如何可以，我们可以加个联系方式，交流更直接。

**Comment by ydniuyongjie** [comment]
我的EMAIL：niuyongjie@163.com
