### ISSUE TITLE
Can't install this plugin.

### ISSUE THREAD

**Issue by neuromaancer** [l0o0/tara#24]
The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

My zotero version is 6.0.30.

**Comment by Berlin000000** [comment]
> The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.
> 
> My zotero version is 6.0.30.

me too

**Comment by Berlin000000** [comment]
> The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.
> 
> My zotero version is 6.0.30.

My zotero version is the same as yours, have you solved the problem and do you know which version works?

**Comment by neuromaancer** [comment]
Yeah, the version is not right. This is for Zotero 7. You need just switch the branch to Zotero 6 and download the add-on.
