### ISSUE TITLE
zotero7中导入功能异常

### ISSUE THREAD

**Issue by Kane-9** [l0o0/tara#29]
版本：7.0.0-beta.75+f7dc68c7f (64-bit)
1.设置界面，备份路径选择按钮失效
2.使用导入功能时，系统无反应，没有备份文件选择的弹窗。
3.创建功能创建的备份文件不在Tara_Backup目录下

**Comment by Whut-fmy** [comment]
> 版本：7.0.0-beta.75+f7dc68c7f (64-bit) 1.设置界面，备份路径选择按钮失效 2.使用导入功能时，系统无反应，没有备份文件选择的弹窗。 3.创建功能创建的备份文件不在Tara_Backup目录下
我也是这样

**Comment by imomoe233** [comment]
我也是 点导入没反应

**Comment by moluoheihei** [comment]
点击导入没反应，点击恢复没有之前的备份选项

**Comment by l0o0** [comment]
@moluoheihei @Aspirant-Snail @imomoe233 @Whut-fmy 

应该是 Zotero 插件版本的相关依赖没有更新。最近 Zotero 出了新版本，导致有些不兼容。上面的同学，可以试试这个版本的tara有没有问题 ，记得修改文件扩展名为 xpi
[tara.zip](https://github.com/l0o0/tara/files/15486193/tara.zip)

**Comment by jiyichenhub** [comment]
还是不行，保存失败。
<img width="194" alt="fail" src="https://github.com/l0o0/tara/assets/78127910/4caf7710-24a7-47c4-8545-ee3d29960cdd">

**Comment by tixwho** [comment]
在Zotero版本`7.0.0-beta.104+7e01a7d0e (64-bit)`, Windows与Tara版本`1.0.0-8`上复现问题。

无法使用导入相关功能 (Import/Restore)。点击这两个按钮，没有任何反应。Debug Output中也没有任何输出。

**Comment by yztz** [comment]
如果远程附件同步进来，用新安装的tara恢复的话，看日志应该是找不到插件配置中的itemID配置项
可以试试这样做：
1. **先选中tara的备份条目**
2. 然后在 工具->开发者->Run Javascript中输入：
```javascript
var config = {
    addonName: "Tara",
    addonID: "tara@linxzh.com",
    addonRef: "tara",
    addonInstance: "Tara",
    prefsPrefix: "extensions.zotero.tara",
    releasePage: "https://github.com/l0o0/tara/releases",
    updateJSON: "https://raw.githubusercontent.com/l0o0/tara/main/update.json",
    updateBetaJSON: "https://raw.githubusercontent.com/l0o0/tara/z7/update-beta.json"
  };
function setPref(key, value) {
    return Zotero.Prefs.set(`${config.prefsPrefix}.${key}`, value, true);
  }

function getPref(key) {
    return Zotero.Prefs.get(`${config.prefsPrefix}.${key}`, true);
  }

var selectedItems = ZoteroPane.getSelectedItems();
//selectedItems[0].id;
setPref("itemID", selectedItems[0].id);
getPref("itemID")
```
3. 点击执行，然后再试试看能不能恢复。

**Comment by tixwho** [comment]
原来是id问题！感谢测试。
我前些天使用偷梁换柱的方法也成功了。具体流程是，在要恢复的机器先创建一个备份（这样就在文档库里建立了一个item），然后将要恢复的备份文件拖拽到item上使两者关联，最后使用restore选择版本，恢复成功。
zotero与tara版本均为最新。确实没想到瞎猫撞死耗子的方法能成功，供参考！

**Comment by l0o0** [comment]
> 如果远程附件同步进来，用新安装的tara恢复的话，看日志应该是找不到插件配置中的itemID配置项 可以试试这样做：
> 
>     1. **先选中tara的备份条目**
> 
>     2. 然后在 工具->开发者->Run Javascript中输入：
> 
> 
> ```js
> var config = {
>     addonName: "Tara",
>     addonID: "tara@linxzh.com",
>     addonRef: "tara",
>     addonInstance: "Tara",
>     prefsPrefix: "extensions.zotero.tara",
>     releasePage: "https://github.com/l0o0/tara/releases",
>     updateJSON: "https://raw.githubusercontent.com/l0o0/tara/main/update.json",
>     updateBetaJSON: "https://raw.githubusercontent.com/l0o0/tara/z7/update-beta.json"
>   };
> function setPref(key, value) {
>     return Zotero.Prefs.set(`${config.prefsPrefix}.${key}`, value, true);
>   }
> 
> function getPref(key) {
>     return Zotero.Prefs.get(`${config.prefsPrefix}.${key}`, true);
>   }
> 
> var selectedItems = ZoteroPane.getSelectedItems();
> //selectedItems[0].id;
> setPref("itemID", selectedItems[0].id);
> getPref("itemID")
> ```
> 
>     3. 点击执行，然后再试试看能不能恢复。

原来是这个问题，我猜是我的机器是测试过好多次了，有些备份的itemID一直是存在的。一直复现不了这个错误
