### ISSUE TITLE
Failed in backup as attachment

### ISSUE THREAD

**Issue by jiyichenhub** [l0o0/tara#30]
**Failed in backup as attachment**

<img width="285" alt="bug" src="https://github.com/l0o0/tara/assets/78127910/12457f7d-88b3-4081-b886-90f3b4e54553">

**To Reproduce BUG**

The bug appears in "Create Backup"

**System Information **

- OS ：Win
- Zotero Version ：7.0.0-beta.95+694ccecf4 (64-bit)
- Addon Version ：1.00-9

**Screenshots **

**Comment by l0o0** [comment]
@jiyichenhub  You can try to set a different backup folder, which you have full access to this folder. The user's download folder maybe a good choice, like `C:\Users\<your username here>\Downloads`.

**Comment by jiyichenhub** [comment]
> @jiyichenhub You can try to set a different backup folder, which you have full access to this folder. The user's download folder maybe a good choice, like `C:\Users\<your username here>\Downloads`.

good, problem is well-solved.
