### ISSUE TITLE
最新预览版导入和恢复失效

### ISSUE THREAD

**Issue by llity** [l0o0/tara#32]
导入没反应，恢复没有选项
![image](https://github.com/user-attachments/assets/57876938-9d46-45ed-a4d3-a2be5c98526b)
选择文件夹失效，无法出现弹出选择
![image](https://github.com/user-attachments/assets/c80e48d4-00f0-412a-b510-3715e214a6cf)

**Comment by Rooneyxu** [comment]
mac出现同样的无法恢复的问题

**Comment by l0o0** [comment]
@llity 是不是创建备份后，再点了恢复 ? 应该是插件bug，会在新版本修复
