### ISSUE TITLE
在新设备中，解压备份文件、安装插件失败

### ISSUE THREAD

**Issue by WenxuanZhao** [l0o0/tara#5]
尊敬的作者：
       首先感谢您制作的插件。我在试图同步zotero配置中出现如图问题，特向您反馈，并寻求指点。希望您在百忙之中可以给予解答。
![image](https://user-images.githubusercontent.com/30493911/216786866-65e6e92d-28b7-4b9e-84f3-ee3052ba7850.png)

**Comment by l0o0** [comment]
为什么你这个备份文件上有链接符号？

**Comment by WenxuanZhao** [comment]
> 为什么你这个备份文件上有链接符号？前面的ERROR，我怀疑是不是解压出现了问题

这个截图是我在我另一个电脑B（准备加载原设置的电脑）上截的图。备份文件上有链接符号我认为是我使用坚果云同步zotero导致（再原电脑A上使用插件导出，电脑B上会自动出现备份文件）。
另，我也是不太会坚果云同步zotero，保险起见我使用了三种备份方式，①storage文件夹所在的zotero文件夹事先被我用坚果云整体同步了，②zotero中我设置的同步也改成了坚果云的协议，③使用zotfile插件也进行了同步配置。
我用您开发的插件尝试了好几次解压，每次都是上图的样子，因为我手动调整了一些设置所以我也不知道有没有设置同步。

**Comment by Alex-wangwang** [comment]
同样是这个问题，不晓得提问者解决了没

**Comment by jybhaha** [comment]
一样。
从macos 备份，在windows恢复是遇见这样的问题。

**Comment by ozzzzj** [comment]
Hello,在新电脑安装时依然有上图一样的问题。请问有什么其他的解决办法吗？

**Comment by Jrebort** [comment]
> [tara.xpi.zip](https://github.com/l0o0/tara/files/10898448/tara.xpi.zip) 上面的同学，你们试试安装这个版本，记得把后缀名改为xpi。 这个版本的菜单里加了一个导入按钮，点击之后，你可以选择你电脑上的备份文件

这个可以，希望作者可以继续优化这个插件，解决问题~

**Comment by WenxuanZhao** [comment]
> [tara.xpi.zip](https://github.com/l0o0/tara/files/10898448/tara.xpi.zip) 上面的同学，你们试试安装这个版本，记得把后缀名改为xpi。 这个版本的菜单里加了一个导入按钮，点击之后，你可以选择你电脑上的备份文件

你好，我重新安装了003版本的插件。但依旧是解压缩失败。
我的使用场景是下图描述的场景。
![image](https://github.com/l0o0/tara/assets/30493911/8a1fe9e1-65aa-4678-83bd-25292700d359)

**Comment by WenxuanZhao** [comment]
> [tara.xpi.zip](https://github.com/l0o0/tara/files/10898448/tara.xpi.zip) 上面的同学，你们试试安装这个版本，记得把后缀名改为xpi。 这个版本的菜单里加了一个导入按钮，点击之后，你可以选择你电脑上的备份文件

依旧是原先的报错。安装了这个版本后我重启了zotero，使用导入和恢复均为下图报错。
![image](https://github.com/l0o0/tara/assets/30493911/7f227c12-467a-4048-b3ee-f9f67c21e310)

**Comment by WenxuanZhao** [comment]
我注意到003版本插件会创建一个新的名字为“tmp”的文件夹，里面有“Backup”子文件夹，“Backup”子文件夹中有四个文件夹“extensions”“locate”“styles”“translators”前三个文件夹均为空文件夹。但压缩文件中似乎有文件应当出现在前三个文件夹中（压缩文件中还有个backup.json不知道如何归类）。可否手动把文件解压到文件夹中，然后手动同步？

**Comment by WenxuanZhao** [comment]
我提交了一份日志
[debug output.zip](https://github.com/l0o0/tara/files/11929229/debug.output.zip)
D1741086333

**Comment by WenxuanZhao** [comment]
> > 我提交了一份日志 [debug output.zip](https://github.com/l0o0/tara/files/11929229/debug.output.zip) D1741086333
> 
> 看日志好像是压缩文件过程出错。试试新版，看看还有问题么

抱歉，我最近已经放弃使用zotero，最近一个月内会进行测试，感谢您对项目的维护。

**Comment by xv1smile** [comment]
> > 我提交了一份日志 [debug output.zip](https://github.com/l0o0/tara/files/11929229/debug.output.zip) D1741086333
> 
> 看日志好像是压缩文件过程出错。试试新版，看看还有问题么

我也出了这个问题，我试着新导出一个备份，删光里面的文件再把旧备份的文件挪进去也还是不行，看来是完蛋了

**Comment by l0o0** [comment]
> > > 我提交了一份日志 [debug output.zip](https://github.com/l0o0/tara/files/11929229/debug.output.zip) D1741086333
> > 
> > 
> > 看日志好像是压缩文件过程出错。试试新版，看看还有问题么
> 
> 抱歉，我最近已经放弃使用zotero，最近一个月内会进行测试，感谢您对项目的维护。

如果弃用了，就不必麻烦测试了。安装什么怪麻烦的

**Comment by l0o0** [comment]
> > > 我提交了一份日志 [debug output.zip](https://github.com/l0o0/tara/files/11929229/debug.output.zip) D1741086333
> > 
> > 
> > 看日志好像是压缩文件过程出错。试试新版，看看还有问题么
> 
> 我也出了这个问题，我试着新导出一个备份，删光里面的文件再把旧备份的文件挪进去也还是不行，看来是完蛋了

你是什么版本的 Zotero 与插件？

**Comment by dawnlh** [comment]
zotero 6.0.36， 插件0.0.6，遇到了相同的问题
