### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by lvfeinan** [l0o0/tara#7]
您好，感谢开发
多处`取消`按键`cancel`似乎出现的拼写错误，错误拼写为`cancle`
望后续版本更正
![image](https://user-images.githubusercontent.com/35051948/218443793-19bab987-cef7-42ec-842a-098ebe9a1caa.png)
![image](https://user-images.githubusercontent.com/35051948/218443717-bc921898-c7ab-4758-8799-0949e781c53c.png)

**Comment by l0o0** [comment]
感谢同学的指正，我确实拼错了😅

Lvfn ***@***.***> 于2023年2月13日周一 19:17写道：
